version: '3'
services:
  db:
    image: mysql:8
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recruitment_task
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/recruitment_task"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: recruitment_task
      DB_PASSWORD: password
      DB_HOST: db
